-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 12:43:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema musb_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `musb_db` ;

-- -----------------------------------------------------
-- Schema musb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musb_db` DEFAULT CHARACTER SET utf8 ;
USE `musb_db` ;

-- -----------------------------------------------------
-- Table `musb_db`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`sede` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`sede` (
  `id` INT(3) NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `url_mapa` VARCHAR(512) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `rector` VARCHAR(80) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `telefono` INT(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`facultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`facultad` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`facultad` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `decano` VARCHAR(80) NOT NULL,
  `oficina` VARCHAR(80) NOT NULL,
  `ext` INT(5) NOT NULL,
  `sede` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facultad_sede_idx` (`sede` ASC),
  CONSTRAINT `fk_facultad_sede`
    FOREIGN KEY (`sede`)
    REFERENCES `musb_db`.`sede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`programa` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`programa` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `director` VARCHAR(80) NOT NULL,
  `oficina` VARCHAR(80) NOT NULL,
  `ext` INT(5) NOT NULL,
  `facultad` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_programa_facultad_idx` (`facultad` ASC),
  CONSTRAINT `fk_programa_facultad`
    FOREIGN KEY (`facultad`)
    REFERENCES `musb_db`.`facultad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`usuario` (
  `codigo` INT(11) NOT NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `num_doc` INT(15) NOT NULL,
  `nombres` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `contrasenia` VARCHAR(256) NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  `foto` LONGBLOB NULL,
  `telefono` INT(15) NULL,
  `programa` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Usuario_Programa_idx` (`programa` ASC),
  UNIQUE INDEX `cedula_UNIQUE` (`num_doc` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  CONSTRAINT `fk_Usuario_Programa`
    FOREIGN KEY (`programa`)
    REFERENCES `musb_db`.`programa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`amigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`amigo` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`amigo` (
  `usuario` INT(11) NOT NULL,
  `amigo` INT(11) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `relacion` VARCHAR(20) NULL,
  PRIMARY KEY (`usuario`, `amigo`),
  INDEX `fk_amigo_usuario_amigo_idx` (`amigo` ASC),
  INDEX `fk_amigo_usuario_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_amigo_usuario_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `musb_db`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amigo_usuario_amigo`
    FOREIGN KEY (`amigo`)
    REFERENCES `musb_db`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`tipo_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`tipo_actividad` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`tipo_actividad` (
  `id` INT(3) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`actividad` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`actividad` (
  `id` INT(6) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `tipo` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_tipo_actividad_idx` (`tipo` ASC),
  CONSTRAINT `fk_actividad_tipo_actividad`
    FOREIGN KEY (`tipo`)
    REFERENCES `musb_db`.`tipo_actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`tipo_lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`tipo_lugar` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`tipo_lugar` (
  `id` INT(3) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`lugar` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`lugar` (
  `id` INT(6) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL,
  `tipo` INT(3) NOT NULL,
  `sede` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lugar_tipo_lugar_idx` (`tipo` ASC),
  INDEX `fk_lugar_sede_idx` (`sede` ASC),
  CONSTRAINT `fk_lugar_tipo_lugar`
    FOREIGN KEY (`tipo`)
    REFERENCES `musb_db`.`tipo_lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_sede`
    FOREIGN KEY (`sede`)
    REFERENCES `musb_db`.`sede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`evento` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`evento` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL,
  `actividad` INT(6) NOT NULL,
  `lugar` INT(6) NOT NULL,
  INDEX `fk_agenda_actividad_idx` (`actividad` ASC),
  INDEX `fk_agenda_lugar_idx` (`lugar` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_agenda_actividad`
    FOREIGN KEY (`actividad`)
    REFERENCES `musb_db`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_lugar`
    FOREIGN KEY (`lugar`)
    REFERENCES `musb_db`.`lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`noticia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`noticia` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`noticia` (
  `id` INT(3) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `foto` LONGBLOB NULL,
  `facultad` INT(4) NULL,
  `programa` INT(4) NULL,
  `sede` INT(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_noticia_facultad_idx` (`facultad` ASC),
  INDEX `fk_noticia_programa_idx` (`programa` ASC),
  INDEX `fk_noticia_sede_idx` (`sede` ASC),
  CONSTRAINT `fk_noticia_facultad`
    FOREIGN KEY (`facultad`)
    REFERENCES `musb_db`.`facultad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_programa`
    FOREIGN KEY (`programa`)
    REFERENCES `musb_db`.`programa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_sede`
    FOREIGN KEY (`sede`)
    REFERENCES `musb_db`.`sede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`rol` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`rol` (
  `id` INT(3) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`usuario_rol` (
  `usuario` INT(11) NOT NULL,
  `rol` INT(3) NOT NULL,
  PRIMARY KEY (`usuario`, `rol`),
  INDEX `fk_usuario_rol_rol_idx` (`rol` ASC),
  INDEX `fk_usuario_rol_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario_has_rol_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `musb_db`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_rol_rol`
    FOREIGN KEY (`rol`)
    REFERENCES `musb_db`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`chat` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`chat` (
  `id` INT(7) NOT NULL,
  `mensaje` LONGTEXT NOT NULL,
  `marca_tiempo` DATETIME NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `envia` INT(11) NOT NULL,
  `recibe` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_usuario_envia_idx` (`envia` ASC),
  INDEX `fk_chat_usuario_recibe_idx` (`recibe` ASC),
  CONSTRAINT `fk_chat_usuario_envia`
    FOREIGN KEY (`envia`)
    REFERENCES `musb_db`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_usuario_recibe`
    FOREIGN KEY (`recibe`)
    REFERENCES `musb_db`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `musb_db`.`agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `musb_db`.`agenda` ;

CREATE TABLE IF NOT EXISTS `musb_db`.`agenda` (
  `usuario` INT(11) NOT NULL,
  `evento` INT(10) NOT NULL,
  `papel` ENUM("organizador", "asistente") NOT NULL,
  PRIMARY KEY (`usuario`, `evento`),
  INDEX `fk_agenda_evento_idx` (`evento` ASC),
  INDEX `fk_agenda_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_agenda_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `musb_db`.`usuario` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_evento`
    FOREIGN KEY (`evento`)
    REFERENCES `musb_db`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
